export const MEASURE_TYPES = {
  WATER: 'WATER',
  GAS: 'GAS',
};

export const ERROR_CODES = {
  INVALID_DATA: 'INVALID_DATA',
  MEASURE_NOT_FOUND: 'MEASURE_NOT_FOUND',
  CONFIRMATION_DUPLICATE: 'CONFIRMATION_DUPLICATE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};
